# Generated by Django 3.1.5 on 2021-03-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_subcategory_quick_search_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='quick_search_data',
        ),
    ]
