# Generated by Django 3.1.3 on 2021-04-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('reader_count', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
                ('year_published', models.IntegerField()),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paper_subcategory_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_of_subcategories', to='paper.paper')),
                ('paper_subcategory_1', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='paper_subcategory_1', to='topic.topic')),
                ('paper_subcategory_2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_subcategory_2', to='topic.topic')),
            ],
            options={
                'unique_together': {('paper_subcategory_1', 'paper_subcategory_2', 'paper')},
            },
        ),
    ]
