# Generated by Django 3.1.3 on 2021-04-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paper_subcategory_relationship',
            new_name='paper_topic_relationship',
        ),
        migrations.RenameField(
            model_name='paper_topic_relationship',
            old_name='paper_subcategory_1',
            new_name='paper_topic_1',
        ),
        migrations.RenameField(
            model_name='paper_topic_relationship',
            old_name='paper_subcategory_2',
            new_name='paper_topic_2',
        ),
        migrations.AlterUniqueTogether(
            name='paper_topic_relationship',
            unique_together={('paper_topic_1', 'paper_topic_2', 'paper')},
        ),
    ]
