# Generated by Django 3.1.2 on 2021-01-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20210126_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author_Paper',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='id',
        ),
    ]
