# Generated by Django 3.1.2 on 2021-01-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20210126_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='link',
        ),
    ]
