# Generated by Django 3.1.2 on 2021-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_remove_paper_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
