# Generated by Django 3.1.2 on 2021-01-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_paper_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reader_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
