# Generated by Django 3.1.2 on 2021-01-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0005_delete_keyword_paper'),
        ('paper', '0006_paper_reader_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper_keyword_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='paper.paper')),
                ('paper_keyword_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_keyword_1', to='search_keyword.keyword')),
                ('paper_keyword_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_keyword_2', to='search_keyword.keyword')),
            ],
        ),
    ]
