# Generated by Django 3.1.2 on 2021-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_paper_keyword_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='year_published',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
