# Generated by Django 3.1.2 on 2021-01-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0005_delete_keyword_paper'),
        ('paper', '0008_paper_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_keyword_relationship',
            name='paper_keyword_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_keyword_2', to='search_keyword.keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='paper_keyword_relationship',
            unique_together={('paper_keyword_1', 'paper_keyword_2', 'paper')},
        ),
    ]
