# Generated by Django 3.1.3 on 2021-03-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory_combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combination_authorscore', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combination_growth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combination_pie', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('quick_search_data', models.BooleanField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('subcategory_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_1', to='subcategory.subcategory')),
                ('subcategory_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_2', to='subcategory.subcategory')),
            ],
            options={
                'unique_together': {('subcategory_1', 'subcategory_2')},
            },
        ),
    ]
