# Generated by Django 3.1.3 on 2021-04-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('combinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subcategory_combination',
            new_name='topic_combination',
        ),
    ]
