# Generated by Django 3.1.3 on 2021-04-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('combinations', '0002_auto_20210426_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_combination',
            old_name='subcategory_1',
            new_name='topic_1',
        ),
        migrations.RenameField(
            model_name='topic_combination',
            old_name='subcategory_2',
            new_name='topic_2',
        ),
        migrations.AlterUniqueTogether(
            name='topic_combination',
            unique_together={('topic_1', 'topic_2')},
        ),
    ]
