# Generated by Django 3.1.2 on 2021-01-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0004_auto_20210119_1245'),
        ('combinations', '0002_auto_20210123_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword_combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_reader_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keyword_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_1', to='search_keyword.keyword')),
                ('keyword_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_2', to='search_keyword.keyword')),
            ],
            options={
                'unique_together': {('keyword_1', 'keyword_2')},
            },
        ),
    ]
