# Generated by Django 3.1.2 on 2021-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0003_keyword_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_combination',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
