# Generated by Django 3.1.2 on 2021-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0004_keyword_combination_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_combination',
            name='growth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword_combination',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword_combination',
            name='total_publication',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
