# Generated by Django 3.1.5 on 2021-03-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0004_auto_20210209_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory_combination',
            name='combination_pie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
