# Generated by Django 3.1.3 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0006_auto_20210325_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory_combination',
            name='combination_pie',
            field=models.FloatField(default=0),
        ),
    ]
