# Generated by Django 3.1.3 on 2021-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combinations', '0007_auto_20210325_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory_combination',
            name='combination_pie',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
