# Generated by Django 3.1.3 on 2021-03-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='average_reader_count',
            new_name='keyword_authorscore',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='growth',
            new_name='keyword_growth',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='score',
            new_name='keyword_score',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='total_publication',
        ),
    ]
