# Generated by Django 3.1.2 on 2021-01-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_keyword', '0004_auto_20210119_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword_Paper',
        ),
    ]
